DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "Incidents" CASCADE;
DROP TABLE IF EXISTS "Polls" CASCADE;
DROP TABLE IF EXISTS "PollOptions" CASCADE;
DROP TABLE IF EXISTS "PollVotes" CASCADE;